name: SubsTracker
options:
  bundleIdPrefix: com.subsTracker
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.2"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

targets:
  SubsTracker:
    type: application
    platform: macOS
    sources:
      - path: SubsTracker
        excludes:
          - "**/*.entitlements"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.subsTracker.app
        PRODUCT_NAME: SubsTracker
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_GENERATION_CLASS: ""
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_NSHumanReadableCopyright: ""
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.finance"
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: YES
        SWIFT_EMIT_LOC_STRINGS: YES
        CODE_SIGN_IDENTITY: "-"
