name: SubsTracker
options:
  bundleIdPrefix: com.owerhintdel.substracker
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.2"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

schemes:
  SubsTracker:
    build:
      targets:
        SubsTracker: all
        SubsTrackerTests: [test]
    run:
      executable: SubsTracker
    test:
      targets:
        - SubsTrackerTests

targets:
  SubsTrackerTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: SubsTrackerTests
      - path: SubsTracker/Services/FundingPlannerEngine.swift
      - path: SubsTracker/Services/NotificationDecisions.swift
      - path: SubsTracker/Services/GmailSignalEngine.swift
      - path: SubsTracker/Services/FinanceExportEngine.swift
      - path: SubsTracker/Services/OneTimePurchaseEngine.swift
      - path: SubsTracker/Services/RenewalProjectionEngine.swift
      - path: SubsTracker/Services/TopUpRecommendationEngine.swift
      - path: SubsTracker/Services/RefreshScheduleEngine.swift
      - path: SubsTracker/Services/BackgroundRefreshPolicyEngine.swift
      - path: SubsTracker/Services/UsagePollingEngine.swift
      - path: SubsTracker/Models/Enums.swift
      - path: SubsTracker/Models/GmailModels.swift
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.owerhintdel.substracker.tests
        GENERATE_INFOPLIST_FILE: YES

  SubsTracker:
    type: application
    platform: macOS
    sources:
      - path: SubsTracker
        excludes:
          - "**/*.entitlements"
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.owerhintdel.substracker
        PRODUCT_NAME: SubsTracker
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_GENERATION_CLASS: ""
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_NSHumanReadableCopyright: ""
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.finance"
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: YES
        SWIFT_EMIT_LOC_STRINGS: YES
        CODE_SIGN_ENTITLEMENTS: SubsTracker/SubsTracker.entitlements

  SubsTrackerWidget:
    type: app-extension
    platform: macOS
    sources:
      - path: SubsTrackerWidget
        excludes:
          - "**/*.entitlements"
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.owerhintdel.substracker.widget
        PRODUCT_NAME: SubsTrackerWidget
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_NSHumanReadableCopyright: ""
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_ALLOWED: NO
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_ENTITLEMENTS: SubsTrackerWidget/SubsTrackerWidget.entitlements
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks @executable_path/../../../../Frameworks"
